# =============================================================================
# Kustomization para recursos de Istio
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: istio-finance-app

namespace: finance-app

resources:
  - namespace-injection.yaml
  - service-accounts.yaml
  - peer-authentication.yaml
  - destination-rules.yaml
  - virtual-service.yaml
  - authorization-policy.yaml
  - gateway.yaml
