apiVersion: v1
kind: Service
metadata:
  name: {{ include "finance-app.fullname" . }}-api
  labels:
    {{- include "finance-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "finance-app.selectorLabels" . | nindent 4 }}
    app: finance-api
