apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: finance-app-base

namespace: finance-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: finance-app
    includeSelectors: false