apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: finance-app
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres123"
  POSTGRES_DB: "financedb"
  CONNECTION_STRING: "Host=postgres;Database=financedb;Username=postgres;Password=postgres123"
